name: my_first_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.10.0
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter

  geolocator: ^14.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/haram.png
    - assets/images/madina.jpg
    
