// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0aROGb6q2bL91vxOW6HhYAIrpp5b9P94',
    appId: '1:37216451491:web:4459d91bbd530bf2c03816',
    messagingSenderId: '37216451491',
    projectId: 'rofqa-afd82',
    authDomain: 'rofqa-afd82.firebaseapp.com',
    storageBucket: 'rofqa-afd82.firebasestorage.app',
    measurementId: 'G-ZP9H2N5G0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ28ds5sxcTnBzkE1-T30tjH6aHnrPK3k',
    appId: '1:37216451491:android:465c2d4eb508f4bbc03816',
    messagingSenderId: '37216451491',
    projectId: 'rofqa-afd82',
    storageBucket: 'rofqa-afd82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qPVH7djqAZMCV0t-lCWZnY77knWskCY',
    appId: '1:37216451491:ios:8f0ce66c16222803c03816',
    messagingSenderId: '37216451491',
    projectId: 'rofqa-afd82',
    storageBucket: 'rofqa-afd82.firebasestorage.app',
    iosBundleId: 'com.example.myFristProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-qPVH7djqAZMCV0t-lCWZnY77knWskCY',
    appId: '1:37216451491:ios:8f0ce66c16222803c03816',
    messagingSenderId: '37216451491',
    projectId: 'rofqa-afd82',
    storageBucket: 'rofqa-afd82.firebasestorage.app',
    iosBundleId: 'com.example.myFristProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0aROGb6q2bL91vxOW6HhYAIrpp5b9P94',
    appId: '1:37216451491:web:ea5935a29c9f6a73c03816',
    messagingSenderId: '37216451491',
    projectId: 'rofqa-afd82',
    authDomain: 'rofqa-afd82.firebaseapp.com',
    storageBucket: 'rofqa-afd82.firebasestorage.app',
    measurementId: 'G-MTCZE30ZC9',
  );
}
